<a href="https://colab.research.google.com/github/garganupam/ML/blob/main/Grid_and_randomised_SearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X=df.drop('species',axis=1)
y=df['species']

In [7]:
 X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
model_KN=KNeighborsClassifier(n_neighbors=13)

In [10]:
model_KN.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [11]:
model_KN.score(X_test,y_test)

1.0

In [12]:
from sklearn.svm import SVC
model_svm=SVC(gamma='auto')

In [13]:
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [14]:
model_svm.score(X_test,y_test)

1.0

Using grid search CV for hyperparameter tuning

In [15]:
from sklearn.model_selection import GridSearchCV

In [16]:
classifier=GridSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)

In [17]:
# No need to do train test split in cross validation

In [18]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [19]:
grid_results=pd.DataFrame(classifier.cv_results_)

In [20]:
grid_results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.019271,0.006573,0.017332,0.003926,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.022837,0.004872,0.016363,0.003784,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.019531,0.008490,0.010342,0.002314,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.012738,0.005309,0.010429,0.004282,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.021502,0.006916,0.010868,0.004010,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.012839,0.003100,0.008536,0.003259,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.013089,0.004483,0.010051,0.003842,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.012662,0.002795,0.011729,0.003825,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [21]:
grid_results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [22]:
# Randomised search CV

In [24]:
from sklearn.model_selection import RandomizedSearchCV

In [38]:
classifier_r=RandomizedSearchCV((model_svm),{
    'C':[10,20,30],
    'kernel':['rbf','linear'],
},n_iter=4,cv=5,return_train_score=False)

In [39]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [43]:
randomised_results=pd.DataFrame(classifier_r.cv_results_)

In [44]:
randomised_results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       30       linear         0.960000
1       20          rbf         0.966667
2       20       linear         0.966667
3       10       linear         0.973333